# Generated by Django 4.2.5 on 2023-11-06 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line_ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Line_ministry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.line_ministry'),
        ),
    ]
