# Generated by Django 4.2.5 on 2023-11-18 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Role',
        ),
    ]
