# Generated by Django 4.2.5 on 2023-09-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_user',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
