# Generated by Django 4.2.5 on 2023-11-08 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_line_ministry_alter_customuser_line_ministry'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
