# Generated by Django 4.2.5 on 2023-09-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_rename_user_system_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_user',
            name='Date_of_brth',
            field=models.DateField(default=False),
        ),
    ]
