# Generated by Django 4.2.7 on 2023-11-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_remove_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_LineMinisterHead',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_LineMinisterStaff',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_MoPDHead',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('MoPDHead', 'MoPD Head'), ('LineMinisterHead', 'Line Minister Head')], max_length=20),
        ),
    ]
