# Generated by Django 4.2.5 on 2023-09-25 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_system_user_date_of_brth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system_user',
            name='Date_of_brth',
        ),
        migrations.AddField(
            model_name='system_user',
            name='Date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
