# Generated by Django 4.2.7 on 2023-11-07 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_customuser_line_ministry'),
        ('Account', '0003_customuser_gender'),
    ]

    operations = [
    ]
