# Generated by Django 4.2.5 on 2023-11-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_merge_20231107_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
