# Generated by Django 4.2.7 on 2023-12-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_remove_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_first_time',
            field=models.BooleanField(default=True),
        ),
    ]
