# Generated by Django 4.2.5 on 2023-09-25 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_remove_system_user_date_of_brth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system_user',
            old_name='Date_of_birth',
            new_name='date_of_birth',
        ),
    ]
