# Generated by Django 4.2.5 on 2023-09-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_rename_date_of_birth_system_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_user',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
