# Generated by Django 4.2.5 on 2023-09-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_alter_system_user_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system_user',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
