# Generated by Django 4.2.6 on 2023-10-31 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice',
            field=models.ManyToManyField(blank=True, null=True, to='survey_managment.choice'),
        ),
    ]
