# Generated by Django 4.2.3 on 2023-11-03 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='submitted_id',
        ),
    ]
