# Generated by Django 4.2.5 on 2023-11-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='year_of_experiance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
