# Generated by Django 4.2.7 on 2023-12-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0002_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='to',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
