# Generated by Django 4.2.5 on 2023-11-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0002_question_order_userresponse_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='age',
            field=models.DateField(blank=True, null=True),
        ),
    ]
