# Generated by Django 4.2.7 on 2023-11-18 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
        ('survey_managment', '0002_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='line_ministry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.line_ministry'),
        ),
    ]
