# Generated by Django 4.2 on 2023-10-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0002_department_userresponse_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='allow_doc',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='doc_label',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='has_weight',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='label',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='weight',
            field=models.IntegerField(blank=True),
        ),
    ]
