# Generated by Django 4.2.3 on 2023-11-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0002_remove_userresponse_submitted_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineMinistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
