# Generated by Django 4.2.1 on 2023-10-10 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0002_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='catagory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey_managment.catagory'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey_managment.choice'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey_managment.choice_group'),
        ),
        migrations.AlterField(
            model_name='question',
            name='doc_label',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='label',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
