# Generated by Django 4.2.6 on 2023-10-31 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0002_alter_choice_weight_alter_question_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='catagory',
            new_name='category',
        ),
    ]
