# Generated by Django 4.2.7 on 2023-12-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0003_contactus_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='status',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('pending', 'Pending'), ('recomended', 'Recomended')], default='pending', max_length=20, null=True),
        ),
    ]
