# Generated by Django 4.2.7 on 2023-11-17 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
        ('survey_managment', '0003_remove_question_order_alter_userresponse_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='anonymous_user',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='line_ministry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.line_ministry'),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='status',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('pending', 'Pending')], default='pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
