# Generated by Django 4.2.5 on 2023-10-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0003_alter_question_allow_doc_alter_question_doc_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='forquestion',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='response',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='forsurvey',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='submitted_by',
        ),
        migrations.AlterField(
            model_name='question',
            name='allow_doc',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='doc_label',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='has_weight',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='label',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='weight',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='UserResponse',
        ),
    ]
