# Generated by Django 4.2.3 on 2023-11-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0003_lineministry'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='for_line_ministry',
            field=models.ManyToManyField(null=True, to='survey_managment.lineministry'),
        ),
    ]
