# Generated by Django 4.2.6 on 2023-10-31 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0003_rename_catagory_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'text'), ('number', 'number'), ('radio', 'radio'), ('checkbox', 'checkbox'), ('textarea', 'textarea'), ('url', 'url'), ('email', 'email'), ('date', 'date'), ('rating', 'rating')], max_length=100),
        ),
    ]
