# Generated by Django 4.2.3 on 2023-10-10 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0003_alter_question_catagory_alter_question_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='catagory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey_managment.catagory'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey_managment.choice'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey_managment.choice_group'),
        ),
    ]
