# Generated by Django 4.2.7 on 2023-11-21 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0003_userresponse_line_ministry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='')),
                ('foranswer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_managment.answer')),
            ],
        ),
    ]
