# Generated by Django 4.2.3 on 2023-10-10 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0004_alter_question_catagory_alter_question_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey_managment.survey'),
        ),
    ]
