# Generated by Django 5.0.2 on 2024-03-15 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0004_alter_question_doc_label'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userresponse',
            unique_together=set(),
        ),
    ]
