# Generated by Django 4.2.3 on 2023-11-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_line_ministry_alter_customuser_line_ministry'),
        ('survey_managment', '0004_survey_for_line_ministry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LineMinistry',
        ),
        migrations.AlterField(
            model_name='survey',
            name='for_line_ministry',
            field=models.ManyToManyField(null=True, to='Account.line_ministry'),
        ),
    ]
