# Generated by Django 4.2.7 on 2023-11-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0004_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
