# Generated by Django 4.2.5 on 2023-10-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0005_department_alter_question_allow_doc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choice_group',
        ),
        migrations.AlterField(
            model_name='question',
            name='choice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
