# Generated by Django 4.2.7 on 2023-11-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0005_delete_lineministry_alter_survey_for_line_ministry'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='anonymous_user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
