# Generated by Django 4.2.7 on 2024-04-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0005_alter_userresponse_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
