# Generated by Django 4.2.3 on 2024-01-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0006_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Text', 'text'), ('number', 'number'), ('checkbox', 'checkbox'), ('radio', 'radio'), ('textarea', 'textarea'), ('url', 'url'), ('email', 'email'), ('date', 'date'), ('rating', 'rating')], max_length=100),
        ),
    ]
