# Generated by Django 4.2.5 on 2023-10-16 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0006_remove_question_choice_group_alter_question_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Choice_group',
        ),
    ]
