# Generated by Django 4.2.7 on 2023-12-03 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0005_alter_survey_created_at'),
        ('survey_managment', '0006_remove_userresponse_recommendation_and_more'),
    ]

    operations = [
    ]
