# Generated by Django 4.2.7 on 2024-01-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_customuser_is_first_time'),
        ('survey_managment', '0006_alter_question_question_type_alter_survey_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice',
            field=models.ManyToManyField(blank=True, to='survey_managment.choice'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'text'), ('number', 'number'), ('checkbox', 'checkbox'), ('radio', 'radio'), ('textarea', 'textarea'), ('url', 'url'), ('email', 'email'), ('date', 'date'), ('rating', 'rating')], max_length=100),
        ),
        migrations.AlterField(
            model_name='survey',
            name='for_line_ministry',
            field=models.ManyToManyField(blank=True, to='Account.line_ministry'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='instruction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question',
            field=models.ManyToManyField(blank=True, to='survey_managment.question'),
        ),
    ]
