# Generated by Django 4.2.1 on 2023-10-16 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0007_delete_choice_delete_choice_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('weight', models.IntegerField()),
                ('for_choice_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_managment.choice_group')),
            ],
        ),
    ]
