# Generated by Django 4.2.7 on 2023-11-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0007_userresponse_age_userresponse_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
