# Generated by Django 4.2.7 on 2024-01-29 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_customuser_is_first_time'),
        ('survey_managment', '0007_alter_choice_weight_alter_question_choice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assesment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField(blank=True, null=True)),
                ('start_at', models.DateField(null=True)),
                ('end_at', models.DateField(null=True)),
                ('name', models.CharField(max_length=200)),
                ('for_line_ministry', models.ManyToManyField(blank=True, to='Account.line_ministry')),
                ('survey_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey_managment.surveytype')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateField(auto_now=True, null=True)),
                ('assesment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_managment.assesment')),
                ('question', models.ManyToManyField(blank=True, to='survey_managment.question')),
            ],
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='forsurvey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey_managment.assesment'),
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
    ]
