# Generated by Django 4.2.7 on 2024-01-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_customuser_is_first_time'),
        ('survey_managment', '0008_assesment_section_alter_userresponse_forsurvey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assesment',
            name='created_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='instruction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assesment',
            name='for_line_ministry',
            field=models.ManyToManyField(to='Account.line_ministry'),
        ),
        migrations.RemoveField(
            model_name='section',
            name='assesment',
        ),
        migrations.AlterField(
            model_name='section',
            name='question',
            field=models.ManyToManyField(to='survey_managment.question'),
        ),
        migrations.AddField(
            model_name='section',
            name='assesment',
            field=models.ManyToManyField(to='survey_managment.assesment'),
        ),
    ]
