# Generated by Django 4.2.7 on 2023-11-14 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0008_alter_userresponse_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='anonymous_user',
        ),
    ]
