# Generated by Django 4.2.1 on 2023-10-16 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0008_choice_group_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='for_choice_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey_managment.choice_group'),
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice',
        ),
        migrations.AddField(
            model_name='question',
            name='choice',
            field=models.ManyToManyField(to='survey_managment.choice'),
        ),
    ]
