# Generated by Django 4.2.7 on 2023-12-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0008_contactus_alter_survey_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='sent_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
