# Generated by Django 4.2.1 on 2023-10-16 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0009_alter_choice_for_choice_group_remove_question_choice_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
    ]
