# Generated by Django 4.2.7 on 2024-01-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0009_assesment_created_at_section_instruction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
        migrations.AlterField(
            model_name='question',
            name='allow_doc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='doc_label',
            field=models.TextField(default=0),
        ),
    ]
