# Generated by Django 4.2.7 on 2023-11-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0009_remove_userresponse_anonymous_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='status',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('pending', 'Pending')], default='pending', max_length=20, null=True),
        ),
    ]
