# Generated by Django 4.2.7 on 2023-12-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0009_contactus_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('draft', 'Draft'), ('inbox', 'Inbox'), ('trash', 'Trash')], max_length=10, null=True),
        ),
    ]
