# Generated by Django 4.2.5 on 2023-10-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0010_rename_catagory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Text', 'Text'), ('Number', 'Number'), ('Radio', 'Radio'), ('Checkbox', 'Checkbox'), ('Text-Area', 'Text Area'), ('URL', 'URL'), ('Email', 'Email'), ('Date', 'Date'), ('Rating', 'Rating')], max_length=100),
        ),
    ]
