# Generated by Django 4.2.7 on 2024-01-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0010_remove_question_order_alter_question_allow_doc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='allow_doc',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='has_weight',
            field=models.BooleanField(default=False),
        ),
    ]
