# Generated by Django 4.2.3 on 2023-10-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0010_rename_catagory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='year',
        ),
        migrations.AddField(
            model_name='survey',
            name='end_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='start_at',
            field=models.DateField(null=True),
        ),
    ]
