# Generated by Django 4.2.7 on 2024-01-30 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0011_question_order_alter_question_allow_doc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
    ]
