# Generated by Django 4.2.3 on 2023-10-18 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0012_surveytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey_managment.surveytype'),
        ),
    ]
