# Generated by Django 4.2.7 on 2024-01-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0012_remove_question_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='allow_doc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='doc_label',
            field=models.TextField(),
        ),
    ]
