# Generated by Django 4.2.7 on 2024-01-30 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0013_alter_question_allow_doc_alter_question_doc_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='forsurvey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey_managment.section'),
        ),
    ]
