# Generated by Django 4.2.3 on 2023-10-19 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0012_alter_questionnaire_created_at'),
        ('survey_managment', '0013_survey_survey_type'),
    ]

    operations = [
    ]
