# Generated by Django 4.2.7 on 2024-01-30 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0014_alter_userresponse_forsurvey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresponse',
            old_name='forsurvey',
            new_name='forsection',
        ),
    ]
