# Generated by Django 4.2.3 on 2023-10-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0014_merge_20231019_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='for_choice_group',
        ),
        migrations.RemoveField(
            model_name='question',
            name='for_questionnaire',
        ),
        migrations.AddField(
            model_name='survey',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='instruction',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='question',
            field=models.ManyToManyField(to='survey_managment.question'),
        ),
        migrations.DeleteModel(
            name='Choice_group',
        ),
        migrations.DeleteModel(
            name='Questionnaire',
        ),
    ]
