# Generated by Django 4.2.7 on 2024-01-30 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0015_rename_forsurvey_userresponse_forsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assesment',
            name='instruction',
        ),
    ]
