# Generated by Django 4.2.3 on 2023-10-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0015_remove_questionnaire_survey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choice',
            field=models.ManyToManyField(null=True, to='survey_managment.choice'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question',
            field=models.ManyToManyField(null=True, to='survey_managment.question'),
        ),
    ]
