# Generated by Django 4.2.7 on 2024-01-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0016_remove_assesment_instruction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='assesment',
        ),
        migrations.AddField(
            model_name='assesment',
            name='section',
            field=models.ManyToManyField(to='survey_managment.section'),
        ),
    ]
