# Generated by Django 4.2.3 on 2023-10-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0017_alter_question_choice_alter_question_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
