# Generated by Django 4.2 on 2023-10-26 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0003_alter_question_catagory_alter_question_choice_and_more'),
        ('survey_managment', '0018_alter_survey_created_at'),
    ]

    operations = [
    ]
