# Generated by Django 5.0.2 on 2024-03-13 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0002_userresponse_forassesment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userresponse',
            unique_together={('forsection', 'forassesment')},
        ),
    ]
