# Generated by Django 5.0.2 on 2024-03-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_managment', '0003_alter_userresponse_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='doc_label',
            field=models.TextField(blank=True, null=True),
        ),
    ]
